### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by kainlighty** [U61vashka/VK-API-Bukkit-Bungee#4]
[14:34:36] [Server thread/WARN]: [com.vk.api.sdk.client.ApiRequest] API Server error
com.vk.api.sdk.exceptions.ApiServerException: Internal server error (10): Internal server error
	at com.vk.api.sdk.exceptions.ExceptionMapper.parseException(ExceptionMapper.java:27) ~[VK-API-Bukkit.jar:?]
	at com.vk.api.sdk.client.ApiRequest.executeWithoutRetry(ApiRequest.java:104) ~[VK-API-Bukkit.jar:?]
	at com.vk.api.sdk.client.ApiRequest.execute(ApiRequest.java:79) ~[VK-API-Bukkit.jar:?]
	at com.ubivashka.vk.api.listeners.LongpoolAPIListener.updateLongpoolServer(LongpoolAPIListener.java:82) ~[VK-API-Bukkit.jar:?]
	at com.ubivashka.vk.api.listeners.LongpoolAPIListener.<init>(LongpoolAPIListener.java:30) ~[VK-API-Bukkit.jar:?]
	at com.ubivashka.vk.bukkit.BukkitVkApiPlugin.onEnable(BukkitVkApiPlugin.java:34) ~[VK-API-Bukkit.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560) ~[paper-1.18.2.jar:git-Paper-388]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:665) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:432) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:316) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1164) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-388]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[14:34:36] [Server thread/WARN]: com.vk.api.sdk.exceptions.ApiServerException: Internal server error (10): Internal server error
[14:34:36] [Server thread/WARN]: 	at VK-API-Bukkit.jar//com.vk.api.sdk.exceptions.ExceptionMapper.parseException(ExceptionMapper.java:27)
[14:34:36] [Server thread/WARN]: 	at VK-API-Bukkit.jar//com.vk.api.sdk.client.ApiRequest.executeWithoutRetry(ApiRequest.java:104)
[14:34:36] [Server thread/WARN]: 	at VK-API-Bukkit.jar//com.vk.api.sdk.client.ApiRequest.execute(ApiRequest.java:79)
[14:34:36] [Server thread/WARN]: 	at VK-API-Bukkit.jar//com.ubivashka.vk.api.listeners.LongpoolAPIListener.updateLongpoolServer(LongpoolAPIListener.java:82)
[14:34:36] [Server thread/WARN]: 	at VK-API-Bukkit.jar//com.ubivashka.vk.api.listeners.LongpoolAPIListener.<init>(LongpoolAPIListener.java:30)
[14:34:36] [Server thread/WARN]: 	at VK-API-Bukkit.jar//com.ubivashka.vk.bukkit.BukkitVkApiPlugin.onEnable(BukkitVkApiPlugin.java:34)
[14:34:36] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[14:34:36] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[14:34:36] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541)
[14:34:36] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560)
[14:34:36] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474)
[14:34:36] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:665)
[14:34:36] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:432)
[14:34:36] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:316)
[14:34:36] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1164)
[14:34:36] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[14:34:36] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[14:34:36] [Server thread/ERROR]: Error occurred while enabling VK-API v0.4.0 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "com.vk.api.sdk.objects.groups.responses.GetLongPollServerResponse.getTs()" because "this.longserver" is null
	at com.ubivashka.vk.api.listeners.LongpoolAPIListener.<init>(LongpoolAPIListener.java:31) ~[VK-API-Bukkit.jar:?]
	at com.ubivashka.vk.bukkit.BukkitVkApiPlugin.onEnable(BukkitVkApiPlugin.java:34) ~[VK-API-Bukkit.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560) ~[paper-1.18.2.jar:git-Paper-388]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:665) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:432) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:316) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1164) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-388]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[14:34:36] [Server thread/INFO]: [VK-API] Disabling VK-API v0.4.0

**Comment by bivashy** [comment]
Это не проблема VK-API.
А серверов VK `com.vk.api.sdk.exceptions.ApiServerException: Internal server error (10): Internal server error` значит следующее 

"Произошла внутренняя ошибка сервера. Попробуйте повторить запрос позже."

https://dev.vk.com/reference/errors

UPD: Если ты не понял текст выше, то это значит что проблемы на стороне ВК, не на стороне плагина.

**Comment by kainlighty** [comment]
Я тупанул и только потом осознал что проблема на вк стороне. МОжешь делитнуть в принципе
